name: dev_kit
description: "A development kit for Flutter projects, providing common utilities and extensions."
version: 0.0.1
homepage: https://github.com/venhdev/flutter_dev_kit
repository: https://github.com/venhdev/flutter_dev_kit

environment:
  sdk: ">=2.17.0 <4.0.0"
  # flutter: ">=1.17.0"

dependencies:

dev_dependencies:
  lints: any
  test: ^1.24.0
